<Project Sdk="MSTest.Sdk/4.0.2">

  <ItemGroup>
    <ProjectReference Include="..\..\src\EntraNHI.Cli\EntraNHI.Cli.csproj" />
    <ProjectReference Include="..\..\src\EntraNHI.Application\EntraNHI.Application.csproj" />
    <ProjectReference Include="..\..\src\EntraNHI.Output\EntraNHI.Output.csproj" />
    <ProjectReference Include="..\..\src\EntraNHI.Core\EntraNHI.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TestingExtensionsProfile>None</TestingExtensionsProfile>
  </PropertyGroup>

</Project>
